In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
#### EĞİTİM ###
path = r'egitim_path/'
all_files = glob.glob(path + "/*.csv")

ddf=pd.DataFrame()
for file in all_files:
    df=pd.read_csv(file,  skipfooter=1, skiprows=8, delimiter=';', thousands='.', names=['A','B','C','D','E'],
                  encoding='windows-1254')
    df=df.reset_index()
    df=df.drop(['A', 'E'], axis=1)
    df.head(20)

    ro=np.arange(0,df.shape[0],12).tolist()
    co=np.arange(0,13,1)

    dfn=pd.DataFrame()
    df1=pd.DataFrame()
    dfn.columns=df1.columns

    for i in ro:
        df1=df.iloc[i:i+12].transpose()
        df1['Şehir']=file
        df1.columns=co[:13]
        
        df1['İlçe1']=df1[0][0]
        dfn=dfn.append(df1)


    dfn=dfn.reset_index()
    m=dfn['index']=='index'
    col=dfn[m].iloc[0]
    col[-2]='Şehir'
    col[-1]='İlçe'
    col[0]='Cinsiyet'
    dfn.columns=col

    dfn=dfn.apply(lambda x: x.replace('-', '0'))


    dfn=dfn[~m]
    
    lis=['Okuma yazma bilmeyen',
           'Okuma yazma bilen fakat bir okul bitirmeyen', 'İlkokul',
           'İlköğretim', 'Ortaokul veya dengi okul', 'Lise veya dengi okul',
           'Yüksekokul veya fakülte', 'Yüksek lisans', 'Doktora',
           'Bilinmeyen', 'Toplam']
    for i in lis:
        dfn[i]=pd.to_numeric(dfn[i], errors='ignore')
    ddf=ddf.append(dfn)
    
ddf['Şehir']=ddf['Şehir'].apply(lambda x: x.replace('egitim_path\\', ''))
ddf['Şehir']=ddf['Şehir'].apply(lambda x: x.replace('.xls.csv',''))
ddf['Şehir']=ddf['Şehir'].apply(lambda x: x.title())
ddf['Şehir']=ddf['Şehir'].apply(lambda x: x.replace('I', 'İ'))
ddf['Şehir']=ddf['Şehir'].apply(lambda x: x.replace('İsparta', 'Isparta'))
ddf['Şehir']=ddf['Şehir'].apply(lambda x: x.replace('İğdır', 'Iğdır'))

fin=ddf.drop('index', axis=1)
    
###

col=fin.columns.tolist()
col=['Şehir', 'İlçe', 'Cinsiyet',  'Okuma yazma bilmeyen',
     'Okuma yazma bilen fakat bir okul bitirmeyen','İlkokul','İlköğretim','Ortaokul veya dengi okul',
     'Lise veya dengi okul','Yüksekokul veya fakülte','Yüksek lisans','Doktora', 'Bilinmeyen', 'Toplam',]
dfeg=fin[col]
dfeg.to_csv('2018Mv_Egitim.csv', encoding='utf-8')
dfeg.head()

C:\Users\m.c\Anaconda3\envs\newen\lib\site-packages\ipykernel_launcher.py:8: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

,Şehir,İlçe,Cinsiyet,Okuma yazma bilmeyen,Okuma yazma bilen fakat bir okul bitirmeyen,İlkokul,İlköğretim,Ortaokul veya dengi okul,Lise veya dengi okul,Yüksekokul veya fakülte,Yüksek lisans,Doktora,Bilinmeyen,Toplam
1,Adana,Aladağ,Erkek,91,288,1358,1431,750,1605,625,35,2,5,6190
2,Adana,Aladağ,Kadın,826,662,1685,837,541,905,353,7,5,7,5828
3,Adana,Aladağ,Toplam,917,950,3043,2268,1291,2510,978,42,7,12,12018
5,Adana,Ceyhan,Erkek,652,2163,11153,8648,6359,16696,7644,463,34,183,53995
6,Adana,Ceyhan,Kadın,3988,5850,15186,6413,4896,13696,6139,306,37,208,56719